-- Documentación por lead: estado del checklist, archivos privados y permisos.
-- Ejecutar una vez desde el SQL Editor de Supabase.

begin;

create table if not exists public.opportunity_documentation_cases (
  id bigint generated by default as identity primary key,
  opportunity_id bigint not null unique references public.opportunities(id) on delete cascade,
  state jsonb not null default '{}'::jsonb,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.opportunity_documentation_files (
  id uuid primary key default gen_random_uuid(),
  opportunity_id bigint not null references public.opportunities(id) on delete cascade,
  requirement_key text not null,
  file_name text not null,
  storage_path text not null unique,
  mime_type text,
  file_size bigint,
  uploaded_by text,
  created_at timestamptz not null default now()
);

create index if not exists opportunity_documentation_files_opportunity_idx
  on public.opportunity_documentation_files(opportunity_id, requirement_key);

alter table public.opportunity_documentation_cases enable row level security;
alter table public.opportunity_documentation_files enable row level security;

revoke all on table public.opportunity_documentation_cases from anon;
revoke all on table public.opportunity_documentation_files from anon;
grant select, insert, update, delete on table public.opportunity_documentation_cases to authenticated;
grant select, insert, update, delete on table public.opportunity_documentation_files to authenticated;
grant usage, select on sequence public.opportunity_documentation_cases_id_seq to authenticated;

drop policy if exists "documentation_cases_select" on public.opportunity_documentation_cases;
drop policy if exists "documentation_cases_insert" on public.opportunity_documentation_cases;
drop policy if exists "documentation_cases_update" on public.opportunity_documentation_cases;
drop policy if exists "documentation_cases_delete" on public.opportunity_documentation_cases;
drop policy if exists "documentation_files_select" on public.opportunity_documentation_files;
drop policy if exists "documentation_files_insert" on public.opportunity_documentation_files;
drop policy if exists "documentation_files_update" on public.opportunity_documentation_files;
drop policy if exists "documentation_files_delete" on public.opportunity_documentation_files;

create policy "documentation_cases_select"
on public.opportunity_documentation_cases for select to authenticated
using (public.crm_can_read_opportunity(opportunity_id));

create policy "documentation_cases_insert"
on public.opportunity_documentation_cases for insert to authenticated
with check (public.crm_can_write_opportunity(opportunity_id));

create policy "documentation_cases_update"
on public.opportunity_documentation_cases for update to authenticated
using (public.crm_can_write_opportunity(opportunity_id))
with check (public.crm_can_write_opportunity(opportunity_id));

create policy "documentation_cases_delete"
on public.opportunity_documentation_cases for delete to authenticated
using (public.crm_can_write_opportunity(opportunity_id));

create policy "documentation_files_select"
on public.opportunity_documentation_files for select to authenticated
using (public.crm_can_read_opportunity(opportunity_id));

create policy "documentation_files_insert"
on public.opportunity_documentation_files for insert to authenticated
with check (public.crm_can_write_opportunity(opportunity_id));

create policy "documentation_files_update"
on public.opportunity_documentation_files for update to authenticated
using (public.crm_can_write_opportunity(opportunity_id))
with check (public.crm_can_write_opportunity(opportunity_id));

create policy "documentation_files_delete"
on public.opportunity_documentation_files for delete to authenticated
using (public.crm_can_write_opportunity(opportunity_id));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'lead-documentation',
  'lead-documentation',
  false,
  15728640,
  array['application/pdf', 'image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.crm_document_opportunity_id(object_name text)
returns bigint
language plpgsql
immutable
set search_path = public
as $$
begin
  return nullif(split_part(object_name, '/', 1), '')::bigint;
exception when invalid_text_representation then
  return null;
end
$$;

revoke all on function public.crm_document_opportunity_id(text) from public;
grant execute on function public.crm_document_opportunity_id(text) to authenticated;

drop policy if exists "lead_documentation_storage_select" on storage.objects;
drop policy if exists "lead_documentation_storage_insert" on storage.objects;
drop policy if exists "lead_documentation_storage_update" on storage.objects;
drop policy if exists "lead_documentation_storage_delete" on storage.objects;

create policy "lead_documentation_storage_select"
on storage.objects for select to authenticated
using (
  bucket_id = 'lead-documentation'
  and public.crm_can_read_opportunity(public.crm_document_opportunity_id(name))
);

create policy "lead_documentation_storage_insert"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'lead-documentation'
  and public.crm_can_write_opportunity(public.crm_document_opportunity_id(name))
);

create policy "lead_documentation_storage_update"
on storage.objects for update to authenticated
using (
  bucket_id = 'lead-documentation'
  and public.crm_can_write_opportunity(public.crm_document_opportunity_id(name))
)
with check (
  bucket_id = 'lead-documentation'
  and public.crm_can_write_opportunity(public.crm_document_opportunity_id(name))
);

create policy "lead_documentation_storage_delete"
on storage.objects for delete to authenticated
using (
  bucket_id = 'lead-documentation'
  and public.crm_can_write_opportunity(public.crm_document_opportunity_id(name))
);

commit;
